[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "antarctic_plots"
dynamic = ["version"]
authors = [
    {name = "Matt Tankersley", email = "matt.d.tankersley@gmail.com"},
]
description = "Functions to automate Antarctic data visualization"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]
readme = "README.md"
license = {file = "LICENSE"}

keywords = ["antarctica", "maps", "plotting", "pygmt", "cross-section"]

dependencies = [
    "pandas",
    "openpyxl",
    "pooch[progress]", # includes tqdm
    "verde>=1.8.0",
    "xarray[io]", # includes netCDF4, h5netcdf, scipy, pydap, zarr, fsspec, cftime, rasterio, cfgrib, pooch
    "harmonica>=0.6.0",
    "pyproj",
    "matplotlib",
    "pyogrio",
    "rioxarray",
    "scipy",
    "numpy",
    "pygmt",
    "geopandas",
    "zarr",
    "python-dotenv",
    "nptyping",
]

[project.optional-dependencies]
interactive = [
    "geoviews",
    "cartopy",
    "ipyleaflet",
]
viz = [
    "seaborn",
]
test = [
  "pytest >=6",
  "pytest-cov >=3",
  "deepdiff",
]
docs = [
  "sphinx>=4.0",
  "myst_parser",
  "sphinx_copybutton",
  "sphinx_autodoc_typehints",
  "sphinx-book-theme>=0.3",
  "sphinx_design",
  "nbsphinx",
  "nbconvert",
]
dev = [
    "antarctic-plots[interactive,viz,test,docs]",
    "ruff",
    "nox",
    "pre-commit",
    "pylint",
    "python-semantic-release >=8",
    "ipykernel",
]
all = [
  "antarctic-plots[interactive,viz,test,dev,docs]",
]

[project.urls]
homepage = "https://antarctic-plots.readthedocs.io/en/latest/index.html"
repository = "https://github.com/mdtanker/antarctic_plots"
documentation = "https://antarctic-plots.readthedocs.io/en/latest/api.html"

[tool.setuptools]
packages = ["antarctic_plots"]

[tool.setuptools.dynamic]
version = {attr = "antarctic_plots.__version__"}

#[tool.setuptools_scm]
#write_to = "antarctic_plots/_version.py"
#version_scheme= "post-release"

[tool.flake8]
max-line-length = 88

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
    "**/__init__.py"
    ]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "earthdata: marks tests as requiring earthdata login info (deselect with '-m \"not earthdata\"')",
    "issue: mark tests with current issues (deselect with '-m \"not issues\"')",
    "working: marks tests which are working",
    "fetch: marks tests which fetch data",
]