name: polartoolkit-binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - polartoolkit=0.3.3
  # interactive
  - geoviews
  - cartopy
  - ipyleaflet
  - ipython
  # viz
  - seaborn
