# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

# cancel any currently running workflows in this same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    runs-on: ubuntu-latest

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      
      # Install Mambaforge with conda-forge dependencies
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: antarctic_plots
          environment-file: binder/environment.yml
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,nodefaults
          channel-priority: strict
          miniforge-version: latest
          miniforge-variant: Mambaforge
          mamba-version: "*"
          use-mamba: true
          auto-activate-base: false

      # Install dependencies from conda-forge
      - name: Install dependencies
        run: |
          mamba install pytest-cov=4.0.0 
          #pip install --pre --prefer-binary            
                        
      # Show installed pkg information for postmortem diagnostic
      - name: List installed packages
        run: mamba list
       
      # Install antarctic-plots itself
      #- name: Install the package
      #  run: make install
     
#       # Install Python
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       # Install package dependencies
#       - name: Install dependencies
#         run: |
#           $CONDA/bin/conda install pytest-cov=4.0.0 -c conda-forge
#           $CONDA/bin/conda env update --file binder/environment.yml --name base
#           pip install -e .

      # Set EARTHDATA login as environment variables
      # - name: Environment Variables from Dotenv
      #   uses: c-py/action-dotenv-to-setenv@v4
      #   with:
      #     env-file: .env

      # Run tests and create coverage report, try replacing with pytest --cov=antarctic_plots antarctic_plots/tests/
      - name: Run tests with pytest
        run: |
          pytest --cov=. --cov-report=html --cov-report=xml -m "not slow"
      
      # Upload coverage report to codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
