# # This workflow will format the code by running the following Makefile commands:
# # make format
# # make check
# # make license-add
# # make license-check

# name: Format

# on: [pull_request]

# # cancel any currently running workflows in this same PR
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

# jobs:
#   format:
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: ["3.9"]
#     runs-on: ubuntu-latest
#     defaults:
#      run:
#       shell: bash -l {0}
      
#     steps:
#       # Checkout current git repository
#       - name: Checkout
#         uses: actions/checkout@v3.1.0
#         with:
#           fetch-depth: 0

#       - name: Switch to Current Branch
#         run: git checkout ${{ env.BRANCH }}
      
#       # Install Mambaforge with conda-forge dependencies
#       - name: Setup Mambaforge
#         uses: conda-incubator/setup-miniconda@v2.1.1
#         with:
#           activate-environment: env_format
#           environment-file: env/env_format.yml
#           python-version: ${{ matrix.python-version }}
#           channels: conda-forge,nodefaults
#           channel-priority: strict
#           miniforge-version: latest
#           miniforge-variant: Mambaforge
#           mamba-version: "*"
#           use-mamba: true
#           auto-activate-base: false

#       # Show installed pkg information for postmortem diagnostic
#       - name: List installed packages
#         run: |
#           mamba list
      
#       # Format the code
#       - name: Run tests with pytest
#         run: |
#           make format
