# Run tests and upload to Codecov with GitHub Actions
#
# NOTE: Pin actions to a specific commit to avoid having the authentication
# token stolen if the Action is compromised. See the comments and links here:
# https://github.com/pypa/gh-action-pypi-publish/issues/27
#
name: test

on: [push, pull_request]

# Use bash by default in all jobs
defaults:
  run:
    shell: bash

jobs:

  #############################################################################
  # Run tests and upload to codecov
  test:
    name: ${{ matrix.os }} python=${{ matrix.python }} dependencies=${{ matrix.dependencies }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      # Otherwise, the workflow would stop if a single job fails. We want to
      # run all of them to catch failures in different combinations.
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        python:
          - "3.7"
          - "3.10"
        dependencies:
          - latest
          - optional
          - oldest
    env:
      REQUIREMENTS: env/requirements-test.txt
      # Used to tag codecov submissions
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
      DEPENDENCIES: ${{ matrix.dependencies }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install requirements
        run: |
          python -m pip install --requirement requirements.txt
      - name: Run the tests
        run: pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # Don't mark the job as failed if the upload fails for some reason.
          # It does sometimes but shouldn't be the reason for running
          # everything again unless something else is broken.
          fail_ci_if_error: false
